// Runs a real "analyze repo" pass in the browser: fetch from GitHub, score with the real
// formula, upsert into the demo store. Mirrors backend/src/services/analysisPipeline.js,
// minus the LLM step — there is no server here to run Ollama against.
import { validateRepoFormat, fetchRepoMeta, fetchRecentCommits, fetchRecentPullRequests } from './githubClient.js';
import { scoreRisk } from './riskScoring.js';
import { upsertDemoAnalysis } from './demoStore.js';

const NO_LLM_SUMMARY =
  "Live data from GitHub — the risk score below is the real formula running on the real diff. " +
  "This static demo has no backend, so the AI summary step (local Ollama) didn't run for this item.";
const NO_LLM_QUALITY = 'Not available in this static demo — generated by a local LLM in the real app.';

function toRecord(repoFullName, item) {
  const risk = scoreRisk({
    files: item.files,
    additions: item.additions,
    deletions: item.deletions,
    fileListComplete: item.fileListComplete,
  });

  return {
    _id: `live:${repoFullName}:${item.type}:${item.externalId}`,
    repo: repoFullName,
    type: item.type,
    externalId: item.externalId,
    title: item.title,
    author: item.author,
    url: item.url,
    lastAnalyzedAt: new Date().toISOString(),
    summary: NO_LLM_SUMMARY,
    qualityNote: NO_LLM_QUALITY,
    llmAnalysisFailed: false,
    llmOutputMalformed: false,
    riskLevel: risk.level,
    riskScore: risk.score,
    riskReasoning: risk.reasoning,
    diffStats: {
      additions: item.additions,
      deletions: item.deletions,
      changedFiles: item.changedFiles,
      sensitiveFiles: risk.breakdown.sensitiveFiles,
      testFilesIncluded: risk.breakdown.testFilesIncluded,
      diffTruncatedForLLM: false,
      fileListComplete: risk.breakdown.fileListComplete,
    },
  };
}

/**
 * @param {string} repoInput raw "owner/repo" text from the input box
 * @returns {Promise<{repo:string, commitsFetched:number, pullRequestsFetched:number,
 *   itemsSkippedDuringFetch:number, succeeded:number, failed:number, demo:true, liveFromGitHub:true}>}
 */
export async function analyzeRepoLive(repoInput) {
  const { owner, repo } = validateRepoFormat(repoInput);
  const repoFullName = `${owner}/${repo}`;

  // Fails fast with a precise error (404/private, empty, rate limited) before fetching items —
  // same ordering as the real backend.
  await fetchRepoMeta(owner, repo);

  const [commits, pullRequests] = await Promise.all([
    fetchRecentCommits(owner, repo),
    fetchRecentPullRequests(owner, repo),
  ]);

  for (const item of [...commits, ...pullRequests]) {
    upsertDemoAnalysis(toRecord(repoFullName, item));
  }

  return {
    repo: repoFullName,
    commitsFetched: commits.length,
    pullRequestsFetched: pullRequests.length,
    itemsSkippedDuringFetch: 0,
    succeeded: commits.length + pullRequests.length,
    failed: 0,
    demo: true,
    liveFromGitHub: true,
  };
}
